print("Welcome to the tip Calculator!")
bill = float(input("What was the total bill? $"))
tip_percent = float(input("What percentage tip would you like to give? 10, 12, or 15? "))
head_count = int(input("How many people to split the bill? "))
total = round((bill + (bill * tip_percent/100))/head_count, 2)
print("Each person should pay: $" + str(total))